# SonarQube analysis configuration for TalhaoDigital
sonar.projectKey=talhaodigital
sonar.projectName=Talhao Digital
sonar.projectVersion=1.0
sonar.sources=src
sonar.host.url=http://localhost:3000
sonar.login=0a290d9e3ca6c14f304d993e8d8fd2bc2fd409d0
